### PR TITLE
Better typings, No more generic `Function` type. User's can specify input and output types.

### PR DESCRIPTION
**Pull request by Dudeonyx**
Over at the [redux-starter-kit](https://github.com/reduxjs/redux-starter-kit) repo which uses this lib, we are planning to switch to Typescript but the generic `Function` type selectors `selectorator` returns break type safety, so I decided to either switch to `reselect` or help you guys with better typings.

So basically this update allows Users to supply Input & Output type parameters. Even without those it will try to infer the output type from the getComputedValue function.

```js
createSelector<State, Output>
```

Also overloads were added to handle different parameters,

For selectors taking multiple parameters the Input type can be an array
e.g
```js
createSelector<[string, number, string[], boolean ], number>
```

will give the selector this type signature
```js
(state_0: string, state_1: number, state_2: string[], state_3: boolean) => number
```

# Examples

```js
import createSelector from "selectorator";
   
interface State {
   foo: {
        bar: string;
    };
    baz: string;
 };
                            // State is input type, string is output type
   const getBarBaz = createSelector<State, string>(["foo.bar", "baz"], (bar, baz) => {
     return `${bar} ${baz}`;
   });
   
    // getBarBaz() has type signature: (state: State) => string;
   
   const getBarBaz2 = createSelector<any, string>(["foo.bar", "baz"], (bar, baz) => {
       return `${bar} ${baz}`;
   });
   
    // getBarBaz2() has type signature: (state: any) => string;
   
   const getBarBaz3 = createSelector(["foo.bar", "baz"], (bar, baz) => {
       return `${bar} ${baz}`;
   });
  
    // getBarBaz3() has type signature: (state: any) => any;
  
     const getBarBaz4 = createSelector(["foo.bar", "baz", { path: 0, argIndex: 2 }], (bar, baz) => {
        return `${bar} ${baz}`;
    });
   
    // getBarBaz4() has type signature: (...state: any[]) => any;
   
   const getBarBazQux5 = createSelector<[State, string[]],string>(["foo.bar", "baz", { path: 0, argIndex: 2 }], (bar, baz) => {
      return `${bar} ${baz}`;
    });
   
    // getBarBaz5() has type signature: (state_0: State, state_1: string[]) => string;
   
    const getStructuredBarBaz = createSelector({
       barBaz: getBarBaz,
    }});  

  // getStructuredBarBaz() has type signature: (state: any) => ({ barBaz: string });
  
```

### CODE REVIEW

**Comment by planttheidea** [comment]
This is great. I'm pretty new to TypeScript, so the generics were based on my limited knowledge. I'll merge and release this tonight!

**Comment by Dudeonyx** [comment]
In that case I'll try to update the readme to document these changes

**Comment by planttheidea** [comment]
Lemme know if you want me to hold off or additional changes to the `README` or if you're cool with me releasing.

**Comment by Dudeonyx** [comment]
Done

**Comment by planttheidea** [comment]
Alright cool. Unfortunately I just got to work so I won't be about to do the release until tonight, but it'll happen soon as I'm home.

**Comment by planttheidea** [comment]
Alright, this has been released as part of `4.0.2`. Hopefully this helps with `redux-starter-kit`!

**Comment by Dudeonyx** [comment]
Alright, been really busy for the past few days, it's great that this was merged, let me know if you notice any issues with the typings

**Pull request merged**
